name = "GarishPrint"
uuid = "b0ab02a7-8576-43f7-aa76-eaa7c3897c54"
authors = ["Roger-Luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.2.1"

[deps]

[compat]
julia = "1"

[extras]
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DataFrames", "Configurations"]
